name: LevelSystem
version: '${project.version}'
main: me.dragoneisbaer.minecraft.levelsystem.LevelSystem
api-version: '1.20'
load: STARTUP
commands:
  setlevel:
    description: Setzt dein Level.
    usage: /<command>
  setjumpstart:
    description: Setzte den Startpunkt eines JumpNRuns.
    usage: /<command> <name>
  setjumpende:
    description: Setzte den Endpunkt eines JumpNRuns.
    usage: /<command> <name>
  stopjumpnrun:
    description: Stoppt dein JumpNRun.
    usage: /<command>
