name: LevelSystem
version: '${project.version}'
main: me.dragoneisbaer.minecraft.levelsystem.LevelSystem
api-version: '1.20'
load: STARTUP
commands:
  setlevel:
    description: Setzt dein Level.
    usage: /<command> <level>
  setjumpstart:
    description: Setzte den Startpunkt eines JumpNRuns.
    usage: /<command> <name> <difficulty>
  setjumpende:
    description: Setzte den Endpunkt eines JumpNRuns.
    usage: /<command> <name>
  stopjumpnrun:
    description: Stoppt dein JumpNRun.
    usage: /<command>
  reloadjumpnrun:
    description: Reloaded alle deine JumpNRunLocations.
    usage: /<command>
  createleaderboard:
    description: Erstellt ein Leaderboard
    usage: /<command> <name>
  deleteleaderboard:
    description: Löscht ein Leaderboard von einem JumpNRun.
    usage: /<command> <name>